# Generated by Django 5.2.4 on 2025-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('student', 'student'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('guest', 'Guest')], default='superadmin', max_length=20),
        ),
    ]
